---
- name: Patch EC2 instance
  hosts: your_ec2_instance
  become: yes

  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: yes
        update_cache: yes
