---
- name: Install Apache
  hosts: your_target_host
  become: yes
  tasks:
    - name: Update package cache
      apt:
        update_cache: yes

    - name: Install Apache
      apt:
        name: apache2
        state: present
