---
- name: Deploy Apache Tomcat
  hosts: your_target_host_or_group
  become: true
  tasks:
    - name: Install Java Development Kit (JDK)
      apt:
        name: default-jdk
        state: present

    - name: Download Apache Tomcat tarball
      get_url:
        url: "https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.50/bin/apache-tomcat-9.0.50.tar.gz"
        dest: "/tmp/apache-tomcat.tar.gz"

    - name: Extract Apache Tomcat
      unarchive:
        src: "/tmp/apache-tomcat.tar.gz"
        dest: "/opt"
        remote_src: yes
        creates: "/opt/apache-tomcat-9.0.50"

    - name: Start Apache Tomcat service
      systemd:
        name: tomcat
        state: started
        enabled: yes

