---
- name: Install Java
  become: true
  apt:
    name: default-jdk
    state: present

- name: Download Apache Tomcat
  get_url:
    url: "https://archive.apache.org/dist/tomcat/tomcat-8/v8.5.73/bin/apache-tomcat-8.5.73.tar.gz"
    dest: "/tmp/apache-tomcat-8.5.73.tar.gz"

- name: Extract Apache Tomcat
  ansible.builtin.unarchive:
    src: "/tmp/apache-tomcat-8.5.73.tar.gz"
    dest: "/opt"
    remote_src: yes

- name: Set ownership and permissions on Apache Tomcat directory
  ansible.builtin.file:
    path: "/opt/apache-tomcat-8.5.73"
    owner: your_username
    group: your_groupname
    mode: "0755"
    recurse: yes

- name: Start Apache Tomcat service
  ansible.builtin.command: "/opt/apache-tomcat-8.5.73/bin/startup.sh"
  async: 60
  poll: 0
  ignore_errors: yes
